name: cipher_connect
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
      - family: Roboto
        fonts:
          - asset: fonts/Roboto-Regular.ttf
          - asset: fonts/Roboto-Bold.ttf
            weight: 700
      - family: Poppins
        fonts:
          - asset: fonts/Poppins-Regular.ttf
          - asset: fonts/Poppins-Bold.ttf
            weight: 700
  uses-material-design: true
